spring.application.name=agrolink-backend
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.ufmhxrfopuaqmzbeqfxe
spring.datasource.password=Shashin1234#
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PayHere Configuration (Sandbox)
payhere.merchant-id=1233929
payhere.merchant-secret=MjI2MjcwMjQwMTIxMDk0NzQ2MjcyMjc1MTg4NTMxMjQxNjY3Mjg5OA==

# Fix Connection Pool
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
