spring.application.name=agrolink-backend
server.port=8082


# ==============================================================
# Database Configuration
# Database Configuration (TEAM DATABASE - CONNECTED)
spring.datasource.url=jdbc:postgresql://db.wwcymxpjeqshbkllwkfj.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=#Sinolli199
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# Hibernate / JPA (Keep these as they are)
# ==============================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PayHere Configuration (Sandbox) - Keep as is
payhere.merchant-id=1234672
payhere.merchant-secret=Mjc3NTcwOTQwMjU4MDA1OTIzMDM5NzAwMDQwODEzOTQ1NDczNzky

# Fix Connection Pool - Keep as is
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=30000

# ==============================================================
# Mail Configuration (Example for Gmail)
# ==============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sandarunethsaranc@gmail.com
spring.mail.password=zdmx bbvq bvnk fyrp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false